export interface Country {
  name: string;
  flag: string;
  states: string[];
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", flag: "🇦🇫", states: ["Badakhshan", "Balkh", "Herat", "Kabul", "Kandahar", "Nangarhar"] },
  { name: "Albania", flag: "🇦🇱", states: [] },
  { name: "Algeria", flag: "🇩🇿", states: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"] },
  { name: "Andorra", flag: "🇦🇩", states: [] },
  { name: "Angola", flag: "🇦🇴", states: ["Luanda", "Benguela", "Huambo", "Huíla"] },
  { name: "Argentina", flag: "🇦🇷", states: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán", "Salta", "Entre Ríos", "Misiones", "Chaco", "Corrientes", "Santiago del Estero", "San Juan", "Jujuy", "Río Negro", "Neuquén", "Formosa", "Chubut", "San Luis", "Catamarca", "La Rioja", "La Pampa", "Santa Cruz", "Tierra del Fuego"] },
  { name: "Armenia", flag: "🇦🇲", states: [] },
  { name: "Australia", flag: "🇦🇺", states: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "Northern Territory", "Australian Capital Territory"] },
  { name: "Austria", flag: "🇦🇹", states: ["Burgenland", "Carinthia", "Lower Austria", "Upper Austria", "Salzburg", "Styria", "Tyrol", "Vorarlberg", "Vienna"] },
  { name: "Azerbaijan", flag: "🇦🇿", states: [] },
  { name: "Bahamas", flag: "🇧🇸", states: [] },
  { name: "Bahrain", flag: "🇧🇭", states: [] },
  { name: "Bangladesh", flag: "🇧🇩", states: ["Dhaka", "Chittagong", "Rajshahi", "Khulna", "Barisal", "Sylhet", "Rangpur", "Mymensingh"] },
  { name: "Barbados", flag: "🇧🇧", states: [] },
  { name: "Belarus", flag: "🇧🇾", states: ["Brest", "Gomel", "Grodno", "Mogilev", "Minsk", "Vitebsk"] },
  { name: "Belgium", flag: "🇧🇪", states: ["Brussels", "Flanders", "Wallonia"] },
  { name: "Belize", flag: "🇧🇿", states: [] },
  { name: "Benin", flag: "🇧🇯", states: [] },
  { name: "Bhutan", flag: "🇧🇹", states: [] },
  { name: "Bolivia", flag: "🇧🇴", states: ["La Paz", "Santa Cruz", "Cochabamba", "Oruro", "Potosí", "Chuquisaca", "Tarija", "Beni", "Pando"] },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", states: [] },
  { name: "Botswana", flag: "🇧🇼", states: [] },
  { name: "Brazil", flag: "🇧🇷", states: ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"] },
  { name: "Brunei", flag: "🇧🇳", states: [] },
  { name: "Bulgaria", flag: "🇧🇬", states: [] },
  { name: "Burkina Faso", flag: "🇧🇫", states: [] },
  { name: "Burundi", flag: "🇧🇮", states: [] },
  { name: "Cabo Verde", flag: "🇨🇻", states: [] },
  { name: "Cambodia", flag: "🇰🇭", states: [] },
  { name: "Cameroon", flag: "🇨🇲", states: [] },
  { name: "Canada", flag: "🇨🇦", states: ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"] },
  { name: "Central African Republic", flag: "🇨🇫", states: [] },
  { name: "Chad", flag: "🇹🇩", states: [] },
  { name: "Chile", flag: "🇨🇱", states: ["Arica y Parinacota", "Tarapacá", "Antofagasta", "Atacama", "Coquimbo", "Valparaíso", "Santiago", "O'Higgins", "Maule", "Ñuble", "Biobío", "Araucanía", "Los Ríos", "Los Lagos", "Aysén", "Magallanes"] },
  { name: "China", flag: "🇨🇳", states: ["Beijing", "Shanghai", "Tianjin", "Chongqing", "Guangdong", "Jiangsu", "Zhejiang", "Shandong", "Henan", "Sichuan", "Hubei", "Hunan", "Fujian", "Anhui", "Hebei", "Liaoning", "Shaanxi", "Jiangxi", "Guangxi", "Yunnan", "Guizhou", "Heilongjiang", "Jilin", "Inner Mongolia", "Xinjiang", "Gansu", "Shanxi", "Hainan", "Ningxia", "Qinghai", "Tibet"] },
  { name: "Colombia", flag: "🇨🇴", states: ["Amazonas", "Antioquia", "Arauca", "Atlántico", "Bogotá", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda", "San Andrés", "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada"] },
  { name: "Comoros", flag: "🇰🇲", states: [] },
  { name: "Congo", flag: "🇨🇬", states: [] },
  { name: "Costa Rica", flag: "🇨🇷", states: ["San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón"] },
  { name: "Croatia", flag: "🇭🇷", states: [] },
  { name: "Cuba", flag: "🇨🇺", states: [] },
  { name: "Cyprus", flag: "🇨🇾", states: [] },
  { name: "Czech Republic", flag: "🇨🇿", states: [] },
  { name: "Denmark", flag: "🇩🇰", states: [] },
  { name: "Djibouti", flag: "🇩🇯", states: [] },
  { name: "Dominica", flag: "🇩🇲", states: [] },
  { name: "Dominican Republic", flag: "🇩🇴", states: [] },
  { name: "Ecuador", flag: "🇪🇨", states: ["Azuay", "Bolívar", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "El Oro", "Esmeraldas", "Galápagos", "Guayas", "Imbabura", "Loja", "Los Ríos", "Manabí", "Morona Santiago", "Napo", "Orellana", "Pastaza", "Pichincha", "Santa Elena", "Santo Domingo", "Sucumbíos", "Tungurahua", "Zamora-Chinchipe"] },
  { name: "Egypt", flag: "🇪🇬", states: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Port Said", "Suez"] },
  { name: "El Salvador", flag: "🇸🇻", states: [] },
  { name: "Equatorial Guinea", flag: "🇬🇶", states: [] },
  { name: "Eritrea", flag: "🇪🇷", states: [] },
  { name: "Estonia", flag: "🇪🇪", states: [] },
  { name: "Eswatini", flag: "🇸🇿", states: [] },
  { name: "Ethiopia", flag: "🇪🇹", states: ["Addis Ababa", "Afar", "Amhara", "Oromia", "Somali", "Tigray", "SNNPR"] },
  { name: "Fiji", flag: "🇫🇯", states: [] },
  { name: "Finland", flag: "🇫🇮", states: [] },
  { name: "France", flag: "🇫🇷", states: ["Île-de-France", "Provence-Alpes-Côte d'Azur", "Auvergne-Rhône-Alpes", "Occitanie", "Nouvelle-Aquitaine", "Hauts-de-France", "Grand Est", "Brittany", "Normandy", "Pays de la Loire", "Centre-Val de Loire", "Bourgogne-Franche-Comté", "Corsica"] },
  { name: "Gabon", flag: "🇬🇦", states: [] },
  { name: "Gambia", flag: "🇬🇲", states: [] },
  { name: "Georgia", flag: "🇬🇪", states: [] },
  { name: "Germany", flag: "🇩🇪", states: ["Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"] },
  { name: "Ghana", flag: "🇬🇭", states: ["Greater Accra", "Ashanti", "Western", "Eastern", "Central", "Northern", "Volta", "Upper East", "Upper West", "Brong-Ahafo"] },
  { name: "Greece", flag: "🇬🇷", states: ["Attica", "Central Macedonia", "Thessaly", "Western Greece", "Crete", "Eastern Macedonia and Thrace", "Peloponnese"] },
  { name: "Grenada", flag: "🇬🇩", states: [] },
  { name: "Guatemala", flag: "🇬🇹", states: [] },
  { name: "Guinea", flag: "🇬🇳", states: [] },
  { name: "Guinea-Bissau", flag: "🇬🇼", states: [] },
  { name: "Guyana", flag: "🇬🇾", states: [] },
  { name: "Haiti", flag: "🇭🇹", states: [] },
  { name: "Honduras", flag: "🇭🇳", states: [] },
  { name: "Hungary", flag: "🇭🇺", states: [] },
  { name: "Iceland", flag: "🇮🇸", states: [] },
  { name: "India", flag: "🇮🇳", states: ["Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Delhi", "Jammu and Kashmir", "Ladakh", "Chandigarh", "Puducherry", "Andaman and Nicobar Islands", "Lakshadweep", "Dadra and Nagar Haveli and Daman and Diu"] },
  { name: "Indonesia", flag: "🇮🇩", states: ["Jakarta", "West Java", "Central Java", "East Java", "Bali", "North Sumatra", "South Sulawesi", "West Kalimantan", "Papua", "Yogyakarta"] },
  { name: "Iran", flag: "🇮🇷", states: ["Tehran", "Isfahan", "Fars", "Razavi Khorasan", "East Azerbaijan", "Khuzestan", "Mazandaran"] },
  { name: "Iraq", flag: "🇮🇶", states: ["Baghdad", "Basra", "Erbil", "Sulaymaniyah", "Nineveh", "Duhok"] },
  { name: "Ireland", flag: "🇮🇪", states: ["Leinster", "Munster", "Connacht", "Ulster"] },
  { name: "Israel", flag: "🇮🇱", states: ["Tel Aviv", "Jerusalem", "Haifa", "Central", "Southern", "Northern"] },
  { name: "Italy", flag: "🇮🇹", states: ["Abruzzo", "Basilicata", "Calabria", "Campania", "Emilia-Romagna", "Friuli Venezia Giulia", "Lazio", "Liguria", "Lombardy", "Marche", "Molise", "Piedmont", "Apulia", "Sardinia", "Sicily", "Trentino-South Tyrol", "Tuscany", "Umbria", "Aosta Valley", "Veneto"] },
  { name: "Jamaica", flag: "🇯🇲", states: [] },
  { name: "Japan", flag: "🇯🇵", states: ["Hokkaido", "Aomori", "Iwate", "Miyagi", "Akita", "Yamagata", "Fukushima", "Ibaraki", "Tochigi", "Gunma", "Saitama", "Chiba", "Tokyo", "Kanagawa", "Niigata", "Toyama", "Ishikawa", "Fukui", "Yamanashi", "Nagano", "Gifu", "Shizuoka", "Aichi", "Mie", "Shiga", "Kyoto", "Osaka", "Hyogo", "Nara", "Wakayama", "Tottori", "Shimane", "Okayama", "Hiroshima", "Yamaguchi", "Tokushima", "Kagawa", "Ehime", "Kochi", "Fukuoka", "Saga", "Nagasaki", "Kumamoto", "Oita", "Miyazaki", "Kagoshima", "Okinawa"] },
  { name: "Jordan", flag: "🇯🇴", states: [] },
  { name: "Kazakhstan", flag: "🇰🇿", states: [] },
  { name: "Kenya", flag: "🇰🇪", states: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Kiambu", "Machakos", "Kajiado", "Uasin Gishu"] },
  { name: "Kiribati", flag: "🇰🇮", states: [] },
  { name: "Kuwait", flag: "🇰🇼", states: [] },
  { name: "Kyrgyzstan", flag: "🇰🇬", states: [] },
  { name: "Laos", flag: "🇱🇦", states: [] },
  { name: "Latvia", flag: "🇱🇻", states: [] },
  { name: "Lebanon", flag: "🇱🇧", states: [] },
  { name: "Lesotho", flag: "🇱🇸", states: [] },
  { name: "Liberia", flag: "🇱🇷", states: [] },
  { name: "Libya", flag: "🇱🇾", states: [] },
  { name: "Liechtenstein", flag: "🇱🇮", states: [] },
  { name: "Lithuania", flag: "🇱🇹", states: [] },
  { name: "Luxembourg", flag: "🇱🇺", states: [] },
  { name: "Madagascar", flag: "🇲🇬", states: [] },
  { name: "Malawi", flag: "🇲🇼", states: [] },
  { name: "Malaysia", flag: "🇲🇾", states: ["Johor", "Kedah", "Kelantan", "Melaka", "Negeri Sembilan", "Pahang", "Penang", "Perak", "Perlis", "Sabah", "Sarawak", "Selangor", "Terengganu", "Kuala Lumpur", "Putrajaya", "Labuan"] },
  { name: "Maldives", flag: "🇲🇻", states: [] },
  { name: "Mali", flag: "🇲🇱", states: [] },
  { name: "Malta", flag: "🇲🇹", states: [] },
  { name: "Marshall Islands", flag: "🇲🇭", states: [] },
  { name: "Mauritania", flag: "🇲🇷", states: [] },
  { name: "Mauritius", flag: "🇲🇺", states: [] },
  { name: "Mexico", flag: "🇲🇽", states: ["Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "México", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"] },
  { name: "Micronesia", flag: "🇫🇲", states: [] },
  { name: "Moldova", flag: "🇲🇩", states: [] },
  { name: "Monaco", flag: "🇲🇨", states: [] },
  { name: "Mongolia", flag: "🇲🇳", states: [] },
  { name: "Montenegro", flag: "🇲🇪", states: [] },
  { name: "Morocco", flag: "🇲🇦", states: ["Casablanca-Settat", "Rabat-Salé-Kénitra", "Marrakech-Safi", "Fès-Meknès", "Tanger-Tétouan-Al Hoceïma", "Souss-Massa"] },
  { name: "Mozambique", flag: "🇲🇿", states: [] },
  { name: "Myanmar", flag: "🇲🇲", states: [] },
  { name: "Namibia", flag: "🇳🇦", states: [] },
  { name: "Nauru", flag: "🇳🇷", states: [] },
  { name: "Nepal", flag: "🇳🇵", states: ["Province No. 1", "Madhesh", "Bagmati", "Gandaki", "Lumbini", "Karnali", "Sudurpashchim"] },
  { name: "Netherlands", flag: "🇳🇱", states: ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "North Brabant", "North Holland", "Overijssel", "South Holland", "Utrecht", "Zeeland"] },
  { name: "New Zealand", flag: "🇳🇿", states: ["Auckland", "Bay of Plenty", "Canterbury", "Gisborne", "Hawke's Bay", "Manawatū-Whanganui", "Marlborough", "Nelson", "Northland", "Otago", "Southland", "Taranaki", "Tasman", "Waikato", "Wellington", "West Coast"] },
  { name: "Nicaragua", flag: "🇳🇮", states: [] },
  { name: "Niger", flag: "🇳🇪", states: [] },
  { name: "Nigeria", flag: "🇳🇬", states: ["Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"] },
  { name: "North Korea", flag: "🇰🇵", states: [] },
  { name: "North Macedonia", flag: "🇲🇰", states: [] },
  { name: "Norway", flag: "🇳🇴", states: ["Oslo", "Viken", "Innlandet", "Vestfold og Telemark", "Agder", "Rogaland", "Vestland", "Møre og Romsdal", "Trøndelag", "Nordland", "Troms og Finnmark"] },
  { name: "Oman", flag: "🇴🇲", states: [] },
  { name: "Pakistan", flag: "🇵🇰", states: ["Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan", "Islamabad Capital Territory", "Azad Kashmir", "Gilgit-Baltistan"] },
  { name: "Palau", flag: "🇵🇼", states: [] },
  { name: "Palestine", flag: "🇵🇸", states: [] },
  { name: "Panama", flag: "🇵🇦", states: [] },
  { name: "Papua New Guinea", flag: "🇵🇬", states: [] },
  { name: "Paraguay", flag: "🇵🇾", states: [] },
  { name: "Peru", flag: "🇵🇪", states: ["Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali"] },
  { name: "Philippines", flag: "🇵🇭", states: ["Metro Manila", "Cebu", "Davao", "Calabarzon", "Central Luzon", "Western Visayas", "Central Visayas", "Northern Mindanao", "Ilocos", "Bicol", "Eastern Visayas", "Zamboanga Peninsula", "Cagayan Valley", "Soccsksargen", "Caraga", "Cordillera", "BARMM"] },
  { name: "Poland", flag: "🇵🇱", states: ["Greater Poland", "Kuyavia-Pomerania", "Lesser Poland", "Łódź", "Lower Silesia", "Lublin", "Lubusz", "Masovia", "Opole", "Podkarpackie", "Podlasie", "Pomerania", "Silesia", "Świętokrzyskie", "Warmia-Masuria", "West Pomerania"] },
  { name: "Portugal", flag: "🇵🇹", states: ["Lisbon", "Porto", "Braga", "Aveiro", "Faro", "Coimbra", "Setúbal", "Leiria", "Viseu", "Madeira", "Azores"] },
  { name: "Qatar", flag: "🇶🇦", states: [] },
  { name: "Romania", flag: "🇷🇴", states: [] },
  { name: "Russia", flag: "🇷🇺", states: ["Moscow", "Saint Petersburg", "Novosibirsk", "Sverdlovsk", "Tatarstan", "Chelyabinsk", "Nizhny Novgorod", "Samara", "Rostov", "Bashkortostan", "Krasnodar", "Krasnoyarsk", "Perm", "Voronezh"] },
  { name: "Rwanda", flag: "🇷🇼", states: [] },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", states: [] },
  { name: "Saint Lucia", flag: "🇱🇨", states: [] },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", states: [] },
  { name: "Samoa", flag: "🇼🇸", states: [] },
  { name: "San Marino", flag: "🇸🇲", states: [] },
  { name: "Sao Tome and Principe", flag: "🇸🇹", states: [] },
  { name: "Saudi Arabia", flag: "🇸🇦", states: ["Riyadh", "Makkah", "Madinah", "Eastern Province", "Asir", "Tabuk", "Hail", "Northern Borders", "Jazan", "Najran", "Al-Baha", "Al-Jawf", "Qassim"] },
  { name: "Senegal", flag: "🇸🇳", states: [] },
  { name: "Serbia", flag: "🇷🇸", states: [] },
  { name: "Seychelles", flag: "🇸🇨", states: [] },
  { name: "Sierra Leone", flag: "🇸🇱", states: [] },
  { name: "Singapore", flag: "🇸🇬", states: [] },
  { name: "Slovakia", flag: "🇸🇰", states: [] },
  { name: "Slovenia", flag: "🇸🇮", states: [] },
  { name: "Solomon Islands", flag: "🇸🇧", states: [] },
  { name: "Somalia", flag: "🇸🇴", states: [] },
  { name: "South Africa", flag: "🇿🇦", states: ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "North West", "Northern Cape", "Western Cape"] },
  { name: "South Korea", flag: "🇰🇷", states: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Sejong", "Gyeonggi", "Gangwon", "North Chungcheong", "South Chungcheong", "North Jeolla", "South Jeolla", "North Gyeongsang", "South Gyeongsang", "Jeju"] },
  { name: "South Sudan", flag: "🇸🇸", states: [] },
  { name: "Spain", flag: "🇪🇸", states: ["Andalusia", "Aragon", "Asturias", "Balearic Islands", "Basque Country", "Canary Islands", "Cantabria", "Castile and León", "Castilla-La Mancha", "Catalonia", "Extremadura", "Galicia", "La Rioja", "Madrid", "Murcia", "Navarre", "Valencian Community"] },
  { name: "Sri Lanka", flag: "🇱🇰", states: ["Central", "Eastern", "North Central", "Northern", "North Western", "Sabaragamuwa", "Southern", "Uva", "Western"] },
  { name: "Sudan", flag: "🇸🇩", states: [] },
  { name: "Suriname", flag: "🇸🇷", states: [] },
  { name: "Sweden", flag: "🇸🇪", states: ["Stockholm", "Västra Götaland", "Skåne", "Östergötland", "Uppsala", "Jönköping", "Halland", "Örebro", "Södermanland", "Dalarna", "Gävleborg", "Värmland", "Norrbotten", "Västerbotten", "Västernorrland", "Kalmar", "Kronoberg", "Blekinge", "Västmanland", "Jämtland", "Gotland"] },
  { name: "Switzerland", flag: "🇨🇭", states: ["Zürich", "Bern", "Lucerne", "Uri", "Schwyz", "Obwalden", "Nidwalden", "Glarus", "Zug", "Fribourg", "Solothurn", "Basel-Stadt", "Basel-Landschaft", "Schaffhausen", "Appenzell Ausserrhoden", "Appenzell Innerrhoden", "St. Gallen", "Graubünden", "Aargau", "Thurgau", "Ticino", "Vaud", "Valais", "Neuchâtel", "Geneva", "Jura"] },
  { name: "Syria", flag: "🇸🇾", states: [] },
  { name: "Taiwan", flag: "🇹🇼", states: ["Taipei", "New Taipei", "Taoyuan", "Taichung", "Tainan", "Kaohsiung", "Hsinchu", "Keelung", "Chiayi", "Hualien", "Changhua", "Pingtung", "Yunlin", "Nantou", "Yilan", "Miaoli"] },
  { name: "Tajikistan", flag: "🇹🇯", states: [] },
  { name: "Tanzania", flag: "🇹🇿", states: ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza", "Zanzibar"] },
  { name: "Thailand", flag: "🇹🇭", states: ["Bangkok", "Chiang Mai", "Chiang Rai", "Chonburi", "Khon Kaen", "Nakhon Ratchasima", "Nonthaburi", "Pathum Thani", "Phuket", "Samut Prakan", "Songkhla", "Surat Thani", "Udon Thani"] },
  { name: "Timor-Leste", flag: "🇹🇱", states: [] },
  { name: "Togo", flag: "🇹🇬", states: [] },
  { name: "Tonga", flag: "🇹🇴", states: [] },
  { name: "Trinidad and Tobago", flag: "🇹🇹", states: [] },
  { name: "Tunisia", flag: "🇹🇳", states: [] },
  { name: "Turkey", flag: "🇹🇷", states: ["Istanbul", "Ankara", "İzmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Mersin", "Kayseri", "Eskişehir", "Diyarbakır", "Samsun", "Trabzon", "Denizli", "Malatya"] },
  { name: "Turkmenistan", flag: "🇹🇲", states: [] },
  { name: "Tuvalu", flag: "🇹🇻", states: [] },
  { name: "Uganda", flag: "🇺🇬", states: [] },
  { name: "Ukraine", flag: "🇺🇦", states: ["Kyiv", "Kharkiv", "Odesa", "Dnipropetrovsk", "Donetsk", "Zaporizhzhia", "Lviv", "Mykolaiv", "Vinnytsia", "Poltava", "Chernihiv", "Cherkasy", "Zhytomyr", "Sumy", "Rivne", "Khmelnytskyi", "Volyn", "Ternopil", "Ivano-Frankivsk", "Chernivtsi", "Zakarpattia", "Kirovohrad", "Luhansk", "Kherson", "Crimea"] },
  { name: "United Arab Emirates", flag: "🇦🇪", states: ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Umm Al Quwain", "Ras Al Khaimah", "Fujairah"] },
  { name: "United Kingdom", flag: "🇬🇧", states: ["England", "Scotland", "Wales", "Northern Ireland"] },
  { name: "United States", flag: "🇺🇸", states: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "District of Columbia"] },
  { name: "Uruguay", flag: "🇺🇾", states: [] },
  { name: "Uzbekistan", flag: "🇺🇿", states: [] },
  { name: "Vanuatu", flag: "🇻🇺", states: [] },
  { name: "Vatican City", flag: "🇻🇦", states: [] },
  { name: "Venezuela", flag: "🇻🇪", states: ["Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Distrito Capital", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia"] },
  { name: "Vietnam", flag: "🇻🇳", states: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hai Phong", "Can Tho", "Binh Duong", "Dong Nai", "Khanh Hoa", "Quang Ninh", "Thanh Hoa", "Nghe An", "Ha Tinh"] },
  { name: "Yemen", flag: "🇾🇪", states: [] },
  { name: "Zambia", flag: "🇿🇲", states: [] },
  { name: "Zimbabwe", flag: "🇿🇼", states: ["Bulawayo", "Harare", "Manicaland", "Mashonaland Central", "Mashonaland East", "Mashonaland West", "Masvingo", "Matabeleland North", "Matabeleland South", "Midlands"] },
];

export const getCountryByName = (name: string): Country | undefined =>
  COUNTRIES.find((c) => c.name === name);
