import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function errorResponse(message: string, status = 400) {
  return new Response(
    JSON.stringify({ success: false, message }),
    { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }
  );
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY");

    if (!supabaseUrl || !serviceRoleKey || !anonKey) {
      console.error("[custom-signup] Missing required environment variables");
      return errorResponse("Server configuration error. Please contact support.", 500);
    }

    let body: Record<string, unknown>;
    try {
      body = await req.json();
    } catch {
      return errorResponse("Invalid request body");
    }

    const { email, password, username, redirectTo, visitor_token } = body as {
      email?: string; password?: string; username?: string; redirectTo?: string; visitor_token?: string;
    };

    if (!email || !password) {
      return errorResponse("Email and password are required");
    }

    const adminClient = createClient(supabaseUrl, serviceRoleKey);

    /** Links a landing_chat_sessions row to a newly registered user and imports chat history */
    async function linkVisitorSession(userId: string, token: string) {
      try {
        const { data: session } = await adminClient
          .from("landing_chat_sessions")
          .update({ user_id: userId } as any)
          .eq("visitor_token", token)
          .is("user_id", null)
          .select()
          .maybeSingle();

        if (!session) {
          console.log(`[signup] No unlinked session found for visitor_token ${token}`);
          return;
        }

        console.log(`[signup] Linked landing chat session ${session.id} -> user ${userId}`);

        const { data: landingMsgs } = await adminClient
          .from("landing_chat_messages")
          .select("*")
          .eq("session_id", session.id)
          .order("created_at", { ascending: true });

        if (!landingMsgs || landingMsgs.length === 0) {
          console.log(`[signup] No visitor messages to import for session ${session.id}`);
          return;
        }

        const { data: convLog, error: convErr } = await adminClient
          .from("ghl_conversation_logs")
          .insert({
            user_id: userId,
            transaction_type: "support",
            amount: 0,
            chat_status: "open",
            conversation_mode: "support",
            game_name: "Visitor Chat",
            game_username: (session as any).name || "visitor",
            message_body: `Imported visitor chat from landing page (${landingMsgs.length} messages)`,
            status: "success",
            contact_id: (session as any).ghl_contact_id || null,
            conversation_id: (session as any).ghl_conversation_id || null,
          })
          .select()
          .single();

        if (convErr || !convLog) {
          console.warn("[signup] Could not create conversation log for visitor history:", convErr);
          return;
        }

        const chatMessages = landingMsgs.map((m: any) => ({
          conversation_log_id: convLog.id,
          user_id: userId,
          body: m.direction === "inbound"
            ? m.body
            : `[Visitor Chat] ${m.body}`,
          direction: m.direction === "outbound" ? "outbound" : "inbound",
          created_at: m.created_at,
        }));

        const { error: insertErr } = await adminClient
          .from("chat_messages")
          .insert(chatMessages);

        if (insertErr) {
          console.warn("[signup] Could not import visitor messages:", insertErr);
        } else {
          console.log(`[signup] Imported ${chatMessages.length} visitor messages into chat for user ${userId}`);
        }
      } catch (e) {
        console.warn("[signup] Could not link visitor session (non-fatal):", e);
      }
    }

    // Username is now auto-generated by the handle_new_user trigger (gamepaneluser###)
    const cleanUsername = (username as string) || "pending";

    // With auto-confirm enabled, signUp returns a valid session immediately
    const anonClient = createClient(supabaseUrl, anonKey);
    const { data: signUpData, error: signUpError } = await anonClient.auth.signUp({
      email: email as string,
      password: password as string,
      options: {
        emailRedirectTo: (redirectTo as string) || undefined,
        data: { username: cleanUsername },
      },
    });

    if (signUpError) {
      return errorResponse(signUpError.message);
    }

    // Double-check: if identities array is empty, this is a "fake" signup for existing user
    if (!signUpData?.user?.identities || signUpData.user.identities.length === 0) {
      return errorResponse("An account with this email already exists. Please login instead.");
    }

    // Verify that the session was returned (auto-confirm is on)
    if (!signUpData?.session) {
      return errorResponse("Account created but auto-login failed. Please try logging in.");
    }

    console.log(`User created: ${email} (auto-confirmed)`);

    // Link landing chat session to the newly registered user (non-blocking)
    if (visitor_token && signUpData?.user?.id) {
      await linkVisitorSession(signUpData.user.id, visitor_token as string);
    }

    // Non-blocking GHL sync for new user
    try {
      const { data: ghlSettings } = await adminClient
        .from("app_settings")
        .select("key, value")
        .in("key", ["GHL_API_KEY", "GHL_LOCATION_ID"]);
      const ghlMap: Record<string, string> = {};
      for (const s of (ghlSettings || [])) ghlMap[s.key] = s.value;
      const ghlKey = ghlMap["GHL_API_KEY"] || Deno.env.get("GHL_API_KEY");
      if (ghlKey) {
        const ghlLoc = ghlMap["GHL_LOCATION_ID"] || Deno.env.get("GHL_LOCATION_ID");
        const ghlUrl = `https://rest.gohighlevel.com/v1/contacts/`;
        await fetch(ghlUrl, {
          method: "POST",
          headers: { Authorization: `Bearer ${ghlKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({ email, name: cleanUsername, ...(ghlLoc ? { locationId: ghlLoc } : {}) }),
        }).catch((e: unknown) => console.error("GHL sync failed:", e));
      }
    } catch (e) { console.error("GHL sync error:", e); }

    // Return session so client can auto-login
    return new Response(
      JSON.stringify({
        success: true,
        session: signUpData.session,
        user: signUpData.user,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "An unexpected error occurred";
    console.error("Error in custom-signup:", error);
    return errorResponse(message, 500);
  }
});
