import { useState, useRef, useCallback } from "react";
import {
  Type,
  Heading,
  Image,
  MousePointerClick,
  Minus,
  GripVertical,
  Trash2,
  ChevronUp,
  ChevronDown,
  Plus,
  Code,
  Eye,
  Paintbrush,
  Upload,
  Loader2,
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

// ── Block types ──────────────────────────────────────────────

export interface EmailBlock {
  id: string;
  type: "header" | "text" | "image" | "button" | "divider";
  props: Record<string, string>;
}

const uid = () => crypto.randomUUID();

const DEFAULT_BLOCKS: Record<EmailBlock["type"], () => EmailBlock> = {
  header: () => ({
    id: uid(),
    type: "header",
    props: {
      text: "Your Heading Here",
      fontSize: "28",
      color: "#f5c518",
      align: "center",
    },
  }),
  text: () => ({
    id: uid(),
    type: "text",
    props: {
      text: "Write your email content here. Use placeholders like {{user_name}} and {{site_name}}.",
      fontSize: "16",
      color: "#ffffff",
      align: "left",
    },
  }),
  image: () => ({
    id: uid(),
    type: "image",
    props: {
      src: "https://placehold.co/600x200/1a1a2e/f5c518?text=Your+Image",
      alt: "Email image",
      width: "100",
    },
  }),
  button: () => ({
    id: uid(),
    type: "button",
    props: {
      text: "Click Here",
      url: "https://example.com",
      bgColor: "#f5c518",
      textColor: "#1a1a2e",
      align: "center",
      borderRadius: "8",
    },
  }),
  divider: () => ({
    id: uid(),
    type: "divider",
    props: {
      color: "#333333",
      thickness: "1",
      spacing: "20",
    },
  }),
};

const BLOCK_PALETTE: { type: EmailBlock["type"]; label: string; icon: typeof Type }[] = [
  { type: "header", label: "Header", icon: Heading },
  { type: "text", label: "Text", icon: Type },
  { type: "image", label: "Image", icon: Image },
  { type: "button", label: "Button", icon: MousePointerClick },
  { type: "divider", label: "Divider", icon: Minus },
];

// ── HTML generation ──────────────────────────────────────────

function blockToHtml(block: EmailBlock): string {
  const p = block.props;
  switch (block.type) {
    case "header":
      return `<h2 style="font-family:Arial,sans-serif;font-size:${p.fontSize}px;color:${p.color};text-align:${p.align};margin:0 0 16px 0;">${p.text}</h2>`;
    case "text":
      return `<p style="font-family:Arial,sans-serif;font-size:${p.fontSize}px;color:${p.color};text-align:${p.align};line-height:1.6;margin:0 0 16px 0;">${p.text}</p>`;
    case "image":
      return `<div style="text-align:center;margin:0 0 16px 0;"><img src="${p.src}" alt="${p.alt}" style="max-width:${p.width}%;height:auto;display:inline-block;border-radius:4px;" /></div>`;
    case "button":
      return `<div style="text-align:${p.align};margin:0 0 16px 0;"><a href="${p.url}" style="display:inline-block;padding:14px 32px;background-color:${p.bgColor};color:${p.textColor};text-decoration:none;font-family:Arial,sans-serif;font-size:16px;font-weight:bold;border-radius:${p.borderRadius}px;">${p.text}</a></div>`;
    case "divider":
      return `<hr style="border:none;border-top:${p.thickness}px solid ${p.color};margin:${p.spacing}px 0;" />`;
    default:
      return "";
  }
}

export function blocksToHtml(blocks: EmailBlock[], bgColor = "#1a1a2e"): string {
  const inner = blocks.map(blockToHtml).join("\n  ");
  return `<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;background:${bgColor};color:#ffffff;">\n  ${inner}\n</div>`;
}

export function htmlToBlocks(html: string): EmailBlock[] | null {
  // Only parse if it was generated by our builder (has data marker or structured divs)
  // Return null to indicate it can't be parsed — keep raw HTML mode
  return null;
}

// ── Image Block Settings (separate component to use hooks) ───

function ImageBlockSettings({
  block,
  onChange,
}: {
  block: EmailBlock;
  onChange: (props: Record<string, string>) => void;
}) {
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const update = (key: string, value: string) =>
    onChange({ ...block.props, [key]: value });

  const inputCls =
    "w-full rounded-md border border-input bg-muted/50 px-3 py-1.5 text-sm text-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary";
  const labelCls = "text-[11px] font-semibold text-muted-foreground uppercase tracking-wider";

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      toast({ title: "Please select an image file", variant: "destructive" });
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      toast({ title: "Image must be under 5MB", variant: "destructive" });
      return;
    }
    setUploading(true);
    const ext = file.name.split(".").pop() || "png";
    const path = `email-images/${crypto.randomUUID()}.${ext}`;
    const { error } = await supabase.storage.from("brand-assets").upload(path, file);
    if (error) {
      toast({ title: "Upload failed", description: error.message, variant: "destructive" });
      setUploading(false);
      return;
    }
    const { data: urlData } = supabase.storage.from("brand-assets").getPublicUrl(path);
    update("src", urlData.publicUrl);
    toast({ title: "Image uploaded!" });
    setUploading(false);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  return (
    <div className="space-y-2">
      <div>
        <label className={labelCls}>Image</label>
        <div className="flex gap-2">
          <input
            value={block.props.src}
            onChange={(e) => update("src", e.target.value)}
            placeholder="https://..."
            className={inputCls + " flex-1"}
          />
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            disabled={uploading}
            className="flex items-center gap-1.5 rounded-md border border-input bg-muted/50 px-3 py-1.5 text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-primary/10 transition-colors disabled:opacity-50"
          >
            {uploading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Upload className="h-3.5 w-3.5" />}
            {uploading ? "..." : "Upload"}
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            onChange={handleUpload}
            className="hidden"
          />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-2">
        <div>
          <label className={labelCls}>Alt Text</label>
          <input
            value={block.props.alt}
            onChange={(e) => update("alt", e.target.value)}
            className={inputCls}
          />
        </div>
        <div>
          <label className={labelCls}>Width %</label>
          <input
            type="number"
            min="10"
            max="100"
            value={block.props.width}
            onChange={(e) => update("width", e.target.value)}
            className={inputCls}
          />
        </div>
      </div>
    </div>
  );
}

// ── Block Settings Panel ─────────────────────────────────────

function BlockSettings({
  block,
  onChange,
}: {
  block: EmailBlock;
  onChange: (props: Record<string, string>) => void;
}) {
  const update = (key: string, value: string) =>
    onChange({ ...block.props, [key]: value });

  const inputCls =
    "w-full rounded-md border border-input bg-muted/50 px-3 py-1.5 text-sm text-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary";
  const labelCls = "text-[11px] font-semibold text-muted-foreground uppercase tracking-wider";

  switch (block.type) {
    case "header":
    case "text":
      return (
        <div className="space-y-2">
          <div>
            <label className={labelCls}>{block.type === "header" ? "Heading" : "Content"}</label>
            {block.type === "text" ? (
              <textarea
                value={block.props.text}
                onChange={(e) => update("text", e.target.value)}
                rows={3}
                className={inputCls + " resize-y"}
              />
            ) : (
              <input
                value={block.props.text}
                onChange={(e) => update("text", e.target.value)}
                className={inputCls}
              />
            )}
          </div>
          <div className="grid grid-cols-3 gap-2">
            <div>
              <label className={labelCls}>Size</label>
              <input
                type="number"
                min="12"
                max="72"
                value={block.props.fontSize}
                onChange={(e) => update("fontSize", e.target.value)}
                className={inputCls}
              />
            </div>
            <div>
              <label className={labelCls}>Color</label>
              <input
                type="color"
                value={block.props.color}
                onChange={(e) => update("color", e.target.value)}
                className="h-8 w-full rounded cursor-pointer border border-input"
              />
            </div>
            <div>
              <label className={labelCls}>Align</label>
              <select
                value={block.props.align}
                onChange={(e) => update("align", e.target.value)}
                className={inputCls}
              >
                <option value="left">Left</option>
                <option value="center">Center</option>
                <option value="right">Right</option>
              </select>
            </div>
          </div>
        </div>
      );

    case "image":
      return <ImageBlockSettings block={block} onChange={onChange} />;

    case "button":
      return (
        <div className="space-y-2">
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className={labelCls}>Label</label>
              <input
                value={block.props.text}
                onChange={(e) => update("text", e.target.value)}
                className={inputCls}
              />
            </div>
            <div>
              <label className={labelCls}>Link URL</label>
              <input
                value={block.props.url}
                onChange={(e) => update("url", e.target.value)}
                className={inputCls}
              />
            </div>
          </div>
          <div className="grid grid-cols-4 gap-2">
            <div>
              <label className={labelCls}>BG</label>
              <input
                type="color"
                value={block.props.bgColor}
                onChange={(e) => update("bgColor", e.target.value)}
                className="h-8 w-full rounded cursor-pointer border border-input"
              />
            </div>
            <div>
              <label className={labelCls}>Text</label>
              <input
                type="color"
                value={block.props.textColor}
                onChange={(e) => update("textColor", e.target.value)}
                className="h-8 w-full rounded cursor-pointer border border-input"
              />
            </div>
            <div>
              <label className={labelCls}>Align</label>
              <select
                value={block.props.align}
                onChange={(e) => update("align", e.target.value)}
                className={inputCls}
              >
                <option value="left">Left</option>
                <option value="center">Center</option>
                <option value="right">Right</option>
              </select>
            </div>
            <div>
              <label className={labelCls}>Radius</label>
              <input
                type="number"
                min="0"
                max="50"
                value={block.props.borderRadius}
                onChange={(e) => update("borderRadius", e.target.value)}
                className={inputCls}
              />
            </div>
          </div>
        </div>
      );

    case "divider":
      return (
        <div className="grid grid-cols-3 gap-2">
          <div>
            <label className={labelCls}>Color</label>
            <input
              type="color"
              value={block.props.color}
              onChange={(e) => update("color", e.target.value)}
              className="h-8 w-full rounded cursor-pointer border border-input"
            />
          </div>
          <div>
            <label className={labelCls}>Thickness</label>
            <input
              type="number"
              min="1"
              max="10"
              value={block.props.thickness}
              onChange={(e) => update("thickness", e.target.value)}
              className={inputCls}
            />
          </div>
          <div>
            <label className={labelCls}>Spacing</label>
            <input
              type="number"
              min="0"
              max="60"
              value={block.props.spacing}
              onChange={(e) => update("spacing", e.target.value)}
              className={inputCls}
            />
          </div>
        </div>
      );

    default:
      return null;
  }
}

// ── Block Preview ────────────────────────────────────────────

function BlockPreview({ block }: { block: EmailBlock }) {
  const p = block.props;
  switch (block.type) {
    case "header":
      return (
        <h2
          style={{
            fontSize: `${p.fontSize}px`,
            color: p.color,
            textAlign: p.align as any,
            margin: 0,
            fontFamily: "Arial, sans-serif",
          }}
        >
          {p.text}
        </h2>
      );
    case "text":
      return (
        <p
          style={{
            fontSize: `${p.fontSize}px`,
            color: p.color,
            textAlign: p.align as any,
            lineHeight: 1.6,
            margin: 0,
            fontFamily: "Arial, sans-serif",
          }}
        >
          {p.text}
        </p>
      );
    case "image":
      return (
        <div style={{ textAlign: "center" }}>
          <img
            src={p.src}
            alt={p.alt}
            style={{
              maxWidth: `${p.width}%`,
              height: "auto",
              borderRadius: 4,
            }}
          />
        </div>
      );
    case "button":
      return (
        <div style={{ textAlign: p.align as any }}>
          <span
            style={{
              display: "inline-block",
              padding: "14px 32px",
              backgroundColor: p.bgColor,
              color: p.textColor,
              fontFamily: "Arial, sans-serif",
              fontSize: 16,
              fontWeight: "bold",
              borderRadius: `${p.borderRadius}px`,
              cursor: "pointer",
            }}
          >
            {p.text}
          </span>
        </div>
      );
    case "divider":
      return (
        <hr
          style={{
            border: "none",
            borderTop: `${p.thickness}px solid ${p.color}`,
            margin: `${p.spacing}px 0`,
          }}
        />
      );
    default:
      return null;
  }
}

// ── Main Builder ─────────────────────────────────────────────

interface EmailBuilderProps {
  html: string;
  onChange: (html: string) => void;
}

export function EmailBuilder({ html, onChange }: EmailBuilderProps) {
  const [blocks, setBlocks] = useState<EmailBlock[]>(() => {
    // Start with some default blocks for new templates
    return [
      DEFAULT_BLOCKS.header(),
      DEFAULT_BLOCKS.text(),
      DEFAULT_BLOCKS.divider(),
      DEFAULT_BLOCKS.text(),
    ];
  });
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [mode, setMode] = useState<"visual" | "html" | "preview">("visual");
  const [bgColor, setBgColor] = useState("#1a1a2e");
  const [draggedIdx, setDraggedIdx] = useState<number | null>(null);
  const [dragOverIdx, setDragOverIdx] = useState<number | null>(null);

  // Sync blocks → HTML
  const syncHtml = useCallback(
    (newBlocks: EmailBlock[], bg = bgColor) => {
      const newHtml = blocksToHtml(newBlocks, bg);
      onChange(newHtml);
    },
    [bgColor, onChange]
  );

  const updateBlocks = (newBlocks: EmailBlock[]) => {
    setBlocks(newBlocks);
    syncHtml(newBlocks);
  };

  const addBlock = (type: EmailBlock["type"]) => {
    const newBlock = DEFAULT_BLOCKS[type]();
    const newBlocks = [...blocks, newBlock];
    updateBlocks(newBlocks);
    setSelectedId(newBlock.id);
  };

  const removeBlock = (id: string) => {
    const newBlocks = blocks.filter((b) => b.id !== id);
    updateBlocks(newBlocks);
    if (selectedId === id) setSelectedId(null);
  };

  const updateBlockProps = (id: string, props: Record<string, string>) => {
    const newBlocks = blocks.map((b) => (b.id === id ? { ...b, props } : b));
    updateBlocks(newBlocks);
  };

  const moveBlock = (fromIdx: number, toIdx: number) => {
    if (toIdx < 0 || toIdx >= blocks.length) return;
    const newBlocks = [...blocks];
    const [moved] = newBlocks.splice(fromIdx, 1);
    newBlocks.splice(toIdx, 0, moved);
    updateBlocks(newBlocks);
  };

  const duplicateBlock = (id: string) => {
    const idx = blocks.findIndex((b) => b.id === id);
    if (idx < 0) return;
    const dup = { ...blocks[idx], id: uid(), props: { ...blocks[idx].props } };
    const newBlocks = [...blocks];
    newBlocks.splice(idx + 1, 0, dup);
    updateBlocks(newBlocks);
    setSelectedId(dup.id);
  };

  // Drag handlers
  const handleDragStart = (idx: number) => setDraggedIdx(idx);
  const handleDragOver = (e: React.DragEvent, idx: number) => {
    e.preventDefault();
    setDragOverIdx(idx);
  };
  const handleDrop = (idx: number) => {
    if (draggedIdx !== null && draggedIdx !== idx) {
      moveBlock(draggedIdx, idx);
    }
    setDraggedIdx(null);
    setDragOverIdx(null);
  };
  const handleDragEnd = () => {
    setDraggedIdx(null);
    setDragOverIdx(null);
  };

  const selectedBlock = blocks.find((b) => b.id === selectedId);

  return (
    <div className="space-y-3">
      {/* Mode toggles */}
      <div className="flex items-center gap-2">
        <div className="flex gap-0.5 rounded-lg bg-muted p-0.5">
          {([
            { key: "visual", label: "Visual", icon: Paintbrush },
            { key: "html", label: "HTML", icon: Code },
            { key: "preview", label: "Preview", icon: Eye },
          ] as const).map((m) => (
            <button
              key={m.key}
              onClick={() => setMode(m.key)}
              className={`flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-all ${
                mode === m.key
                  ? "gradient-bg text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              <m.icon className="h-3.5 w-3.5" />
              {m.label}
            </button>
          ))}
        </div>

        {mode === "visual" && (
          <div className="flex items-center gap-2 ml-auto">
            <span className="text-[11px] text-muted-foreground">BG:</span>
            <input
              type="color"
              value={bgColor}
              onChange={(e) => {
                setBgColor(e.target.value);
                syncHtml(blocks, e.target.value);
              }}
              className="h-6 w-6 rounded cursor-pointer border border-input"
            />
          </div>
        )}
      </div>

      {/* Visual Builder */}
      {mode === "visual" && (
        <div className="grid gap-3 lg:grid-cols-[1fr_280px]">
          {/* Canvas */}
          <div className="space-y-2">
            {/* Block palette */}
            <div className="flex gap-1.5 flex-wrap">
              {BLOCK_PALETTE.map((bp) => (
                <button
                  key={bp.type}
                  onClick={() => addBlock(bp.type)}
                  className="flex items-center gap-1.5 rounded-lg border border-dashed border-border bg-muted/30 hover:bg-primary/10 hover:border-primary/30 px-3 py-1.5 text-xs font-medium text-muted-foreground hover:text-foreground transition-colors"
                >
                  <bp.icon className="h-3.5 w-3.5" />
                  <Plus className="h-3 w-3" />
                  {bp.label}
                </button>
              ))}
            </div>

            {/* Email preview canvas */}
            <div
              className="rounded-lg border border-border overflow-hidden"
              style={{ backgroundColor: bgColor }}
            >
              <div className="max-w-[600px] mx-auto p-5 space-y-0">
                {blocks.length === 0 && (
                  <div className="text-center py-12 opacity-50">
                    <p className="text-sm text-white/60">
                      Click a block type above to start building your email
                    </p>
                  </div>
                )}

                {blocks.map((block, idx) => (
                  <div
                    key={block.id}
                    draggable
                    onDragStart={() => handleDragStart(idx)}
                    onDragOver={(e) => handleDragOver(e, idx)}
                    onDrop={() => handleDrop(idx)}
                    onDragEnd={handleDragEnd}
                    onClick={() => setSelectedId(block.id)}
                    className={`group relative rounded-md transition-all cursor-pointer ${
                      selectedId === block.id
                        ? "ring-2 ring-primary ring-offset-1 ring-offset-transparent"
                        : "hover:ring-1 hover:ring-border"
                    } ${dragOverIdx === idx ? "border-t-2 border-primary" : ""} ${
                      draggedIdx === idx ? "opacity-40" : ""
                    }`}
                    style={{ padding: "8px 4px" }}
                  >
                    {/* Block controls */}
                    <div className="absolute -left-1 top-1/2 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity z-10">
                      <div className="flex flex-col gap-0.5 rounded bg-card border border-border shadow-lg p-0.5">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            moveBlock(idx, idx - 1);
                          }}
                          disabled={idx === 0}
                          className="p-0.5 rounded hover:bg-muted disabled:opacity-30 text-muted-foreground"
                        >
                          <ChevronUp className="h-3 w-3" />
                        </button>
                        <div className="cursor-grab active:cursor-grabbing p-0.5 text-muted-foreground">
                          <GripVertical className="h-3 w-3" />
                        </div>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            moveBlock(idx, idx + 1);
                          }}
                          disabled={idx === blocks.length - 1}
                          className="p-0.5 rounded hover:bg-muted disabled:opacity-30 text-muted-foreground"
                        >
                          <ChevronDown className="h-3 w-3" />
                        </button>
                      </div>
                    </div>

                    {/* Quick actions */}
                    <div className="absolute -right-1 top-0 opacity-0 group-hover:opacity-100 transition-opacity z-10 flex gap-0.5">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          duplicateBlock(block.id);
                        }}
                        className="p-1 rounded bg-card border border-border shadow text-muted-foreground hover:text-foreground text-[10px]"
                        title="Duplicate"
                      >
                        +
                      </button>
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          removeBlock(block.id);
                        }}
                        className="p-1 rounded bg-card border border-border shadow text-muted-foreground hover:text-destructive"
                        title="Delete"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>

                    <BlockPreview block={block} />
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Settings panel */}
          <div className="rounded-lg border border-border bg-card/80 p-3 space-y-3 h-fit">
            <p className="text-xs font-bold text-foreground uppercase tracking-wider">
              Block Settings
            </p>
            {selectedBlock ? (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded-full bg-primary/10 text-primary">
                    {selectedBlock.type}
                  </span>
                </div>
                <BlockSettings
                  block={selectedBlock}
                  onChange={(props) => updateBlockProps(selectedBlock.id, props)}
                />
              </div>
            ) : (
              <p className="text-xs text-muted-foreground">
                Click a block in the canvas to edit its properties
              </p>
            )}
          </div>
        </div>
      )}

      {/* HTML Mode */}
      {mode === "html" && (
        <textarea
          value={html}
          onChange={(e) => onChange(e.target.value)}
          rows={14}
          className="w-full rounded-lg border border-input bg-muted/50 px-4 py-2.5 text-sm text-foreground font-mono placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary resize-y"
        />
      )}

      {/* Preview Mode */}
      {mode === "preview" && (
        <div className="rounded-lg border border-border bg-white p-4 overflow-auto">
          <div dangerouslySetInnerHTML={{ __html: html }} />
        </div>
      )}
    </div>
  );
}
